// <auto-generated />
using System;
using BasicAPI.Features.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BasicAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BasicAPI.Models.Entities.Fornecedor", b =>
                {
                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("for_codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Codigo"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("for_descricao");

                    b.HasKey("Codigo");

                    b.ToTable("tb_fornecedores");
                });

            modelBuilder.Entity("BasicAPI.Models.Entities.Funcionario", b =>
                {
                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fun_codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Codigo"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fun_cpf");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fun_funcao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fun_nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fun_senha");

                    b.HasKey("Codigo");

                    b.ToTable("tb_funcionarios");
                });

            modelBuilder.Entity("BasicAPI.Models.Entities.Produto", b =>
                {
                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pro_codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Codigo"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pro_descricao");

                    b.Property<long>("FornecedorCodigo")
                        .HasColumnType("bigint")
                        .HasColumnName("tb_fornecedores_for_codigo");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("pro_quantidade");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("pro_valor");

                    b.HasKey("Codigo");

                    b.ToTable("tb_produtos");
                });

            modelBuilder.Entity("BasicAPI.Models.Entities.Venda", b =>
                {
                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ven_codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Codigo"));

                    b.Property<long>("FuncionarioCodigo")
                        .HasColumnType("bigint")
                        .HasColumnName("tb_funcionarios_fun_codigo");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ven_horario");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("ven_valor_total");

                    b.HasKey("Codigo");

                    b.ToTable("tb_vendas");
                });

            modelBuilder.Entity("BasicAPI.Models.Entities.VendaItem", b =>
                {
                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ite_codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Codigo"));

                    b.Property<long>("ProdutoCodigo")
                        .HasColumnType("bigint")
                        .HasColumnName("tb_produtos_pro_codigo");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("ite_quantidade");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("ite_valor_produtos");

                    b.Property<long>("VendaCodigo")
                        .HasColumnType("bigint")
                        .HasColumnName("tb_vendas_ven_codigo");

                    b.HasKey("Codigo");

                    b.ToTable("tb_itens");
                });
#pragma warning restore 612, 618
        }
    }
}
